### ISSUE TITLE
Backwards Compatibility 

### ISSUE THREAD

**Issue by MMS-27** [OverShifted/OverEngine#1]
Hi There , Does This Engine Support OpenGl 4.0 and Above?

**Comment by OverShifted** [comment]
Hi, and thanks to open the very first issue on this repo!
__short answer:__
yes
__long answer:__
Currently, OverEngine only supports OpenGL as the graphics API.
It is using [glad2](https://gen.glad.sh/) to load OpenGL API stuff and GLFW for windowing which means you can set the OpenGL version by changing `glfwWindowHint`s [here](https://github.com/OverShifted/OverEngine/blob/master/OverEngine/src/Platform/Windows/WindowsWindow.cpp#L54) and [here](https://github.com/OverShifted/OverEngine/blob/master/OverEngine/src/Platform/Linux/LinuxWindow.cpp#L54).
as you can see it is currently set to `4.6` but it should also work with all `4.x` versions but I haven't tested that out.

**Comment by MMS-27** [comment]
Hi there By Backwards Compatibility I meant whether will Over Engine Support 4.1,4.2,4.3,4.4,4.5 . Currently my System is running  in GL version 4.3 . I have tried cloning your Repository but GLFW is missing I cannot make the project files Thats another problem i am facing . the only error the premake is showing is cannot open vendor/GLFW i tried to make a local copy of GLFW and copy it there but it doesn't work try sorting it out

**Comment by MMS-27** [comment]
If it was possible I Could contribute for the Engine :) .

**Comment by OverShifted** [comment]
Hi again. glfw by default doesn't include a premake file. try cloning [my fork of glfw](https://github.com/OverShifted/glfw). is it the only missing submodule? + make sure to use the `--recursive` flag when cloning like this `git clone --recursive https://github.com/OverShifted/OverEngine` or use `git submodule update --init` if you have already cloned.

I will also make sure all submodules are pointing to the correct commit. It might be my fault! but I don't think so because GitHub actions built the engine for Windows and Linux successfully.

and if your graphics hardware is not supported, It should be a runtime exception and everyone with the `C++17` compiler should be able to compile the engine.

**Comment by OverShifted** [comment]
Gitter is also available [here](https://gitter.im/OverShifted/OverEngine)

**Comment by OverShifted** [comment]
Could you build the engine?

**Comment by MMS-27** [comment]
No , Theres a N number of Errors in my Visual Studio . Could you please make release with the Binary what would be helpful .

**Comment by OverShifted** [comment]
Currently, you can only run Sandbox because Editor is extremely WIP and there is no automated way to import assets and you should make some stuff manually. but here is the Sandbox:
[dev.zip](https://github.com/OverShifted/OverEngine/files/5603964/dev.zip)
FUN FACT: you can edit `assets/scripts/player.lua`.
Changes aren't pushed to GitHub yet.
